AWSTemplateFormatVersion: "2010-09-09"
Description: Template to deploy an S3 bucket.

Resources:
  S3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: firstprobuck

  S3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: secondprobuck

      

